"""
UnknownFormatAgent — adaptive agent for files with unidentified or unusual formats.

Triggered by DatasetDiscovery when a file's extension is missing, misleading,
or maps to a format that couldn't be parsed by standard readers.

Strategy (4 phases):
  1. SNIFF   — magic bytes + text heuristics (format_sniffer)
  2. PROBE   — try 30+ parsers in confidence order (structure_prober)
  3. EXTRACT — deep column/schema analysis (schema_extractor)
  4. ADAPT   — if nothing worked, write a custom parser via LLM,
               validate it, and execute it to produce a standard CSV

Output: FormatDiscovery — a structured description the rest of the pipeline
can use exactly like a normal DatasetProfile entry.

The agent is "adaptive" in three senses:
  a) It dynamically selects which probers to run (based on sniff results)
  b) It generates new code when existing probers all fail
  c) It adjusts its routing hints based on what the schema reveals
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from tools.format_sniffer   import sniff_format,   FormatHint
from tools.content_sampler  import sample_content,  ContentSample
from tools.structure_prober import probe_structure, ProbeResult
from tools.schema_extractor import extract_schema,  SchemaReport


# ------------------------------------------------------------------ #
# Output type                                                          #
# ------------------------------------------------------------------ #

@dataclass
class FormatDiscovery:
    """
    Complete result of the UnknownFormatAgent investigation.
    Compatible with the rest of the pipeline (phases, profiler, orchestrator).
    """
    original_path:   str
    confirmed_format:str            # "csv", "parquet", "sqlite", "binary_unknown", …
    category:        str            # tabular | text | image | audio | binary | archive
    parser_used:     str

    # If the format was decoded successfully
    schema:          Optional[SchemaReport] = None

    # If a custom parser was generated by the LLM
    custom_parser_path: Optional[str] = None   # path to generated .py script
    converted_csv_path: Optional[str] = None   # path to normalised CSV output

    # Routing for the rest of the pipeline
    routing_hints:   dict  = field(default_factory=dict)
    target_candidates: list[str] = field(default_factory=list)

    # Quality
    confidence:      float = 1.0
    warnings:        list[str] = field(default_factory=list)

    # Full narrative for agent context
    summary_text:    str   = ""

    def is_usable(self) -> bool:
        """True if the pipeline can proceed with this file."""
        return self.confirmed_format != "binary_unknown" or self.converted_csv_path is not None


# ------------------------------------------------------------------ #
# Custom parser prompt                                                 #
# ------------------------------------------------------------------ #

_CUSTOM_PARSER_PROMPT = """\
You are a Python expert.  A data file could not be parsed by any standard library.
Here is everything we know about it:

--- File info ---
{file_info}

--- First 256 bytes (hex) ---
{hex_dump}

--- Text preview (first 500 chars) ---
{text_preview}

--- Format hints from magic-byte analysis ---
{hints}

--- Content statistics ---
Entropy: {entropy:.2f}/8.0  |  Null ratio: {null_pct:.1%}  |  Printable: {printable_pct:.1%}

Your task:
Write a single Python script that:
1. Reads the file at path  INPUT_PATH  (use this exact variable — it will be injected)
2. Parses the data into a pandas DataFrame
3. Saves it as a CSV to path  OUTPUT_PATH  (use this exact variable — it will be injected)
4. Prints on the last line:  SCHEMA: <json>  where json has keys:
   {{"rows": <int>, "cols": <int>, "columns": [<list of column names>]}}

Requirements:
- Handle missing values gracefully
- Do not hard-code the file path — use INPUT_PATH and OUTPUT_PATH variables
- Use only stdlib + pandas + numpy (already installed)
- If you need a special library (e.g. h5py, netCDF4, pydicom), add a try/except
  ImportError and fall back to a simpler representation
- Keep the script under 80 lines

Return ONLY the Python code, no markdown fences, no explanation.
"""


# ------------------------------------------------------------------ #
# Agent                                                                #
# ------------------------------------------------------------------ #

class UnknownFormatAgent:
    """
    Adaptive agent that identifies and parses any unknown file format.

    Usage:
        agent = UnknownFormatAgent(llm=get_llm("claude"))
        discovery = agent.investigate("/path/to/mystery.dat")
        print(discovery.summary_text)
    """

    def __init__(self, llm=None, work_dir: str = None, verbose: bool = True):
        """
        Args:
            llm:      LangChain chat model (optional — only needed for custom parser step)
            work_dir: directory for generated files (default: tempdir)
            verbose:  print progress messages
        """
        self.llm      = llm
        self.work_dir = work_dir or tempfile.mkdtemp(prefix="unknown_fmt_")
        self.verbose  = verbose

    # ---------------------------------------------------------------- #
    # Public                                                            #
    # ---------------------------------------------------------------- #

    def investigate(self, path: str) -> FormatDiscovery:
        """
        Full 4-phase investigation of an unknown file.

        Returns a FormatDiscovery regardless of outcome.
        """
        path = str(Path(path).resolve())
        self._log(f"🔍 Investigating: {os.path.basename(path)}")

        # ── Phase 1: Sniff ───────────────────────────────────────────
        self._log("  [1/4] Sniffing magic bytes and heuristics…")
        hints: list[FormatHint] = sniff_format(path)
        self._log(f"       Candidates: {[(h.format, round(h.confidence,2)) for h in hints[:5]]}")

        # ── Phase 2: Content sample ──────────────────────────────────
        self._log("  [2/4] Sampling raw content…")
        cs: ContentSample = sample_content(path)
        if cs.structure_notes:
            self._log(f"       Notes: {cs.structure_notes[:3]}")

        # ── Phase 3: Probe parsers ───────────────────────────────────
        self._log("  [3/4] Probing structure with known parsers…")
        probe: ProbeResult = probe_structure(path, hints)
        self._log(f"       Result: {probe.format} (conf={probe.confidence:.2f}, "
                  f"parser={probe.parser_used})")

        # ── Phase 4a: Extract schema if probe succeeded ──────────────
        schema: Optional[SchemaReport] = None
        custom_parser_path: Optional[str] = None
        converted_csv_path: Optional[str] = None

        if probe.format != "binary_unknown":
            self._log("  [4/4] Extracting deep schema…")
            schema = extract_schema(path, probe)
            self._log(f"       {len(schema.columns)} columns analysed" if schema.columns
                      else "       Non-tabular schema extracted")

        # ── Phase 4b: LLM custom parser if everything failed ─────────
        else:
            if self.llm is not None:
                self._log("  [4/4] All probers failed — asking LLM to write a custom parser…")
                custom_parser_path, converted_csv_path = self._llm_custom_parser(
                    path, hints, cs
                )
                if converted_csv_path:
                    self._log(f"       ✅ Custom parser produced: {converted_csv_path}")
                    # Re-probe the normalised CSV
                    csv_hints = sniff_format(converted_csv_path)
                    probe      = probe_structure(converted_csv_path, csv_hints)
                    schema     = extract_schema(converted_csv_path, probe)
                else:
                    self._log("       ❌ LLM custom parser failed — file remains unreadable")
            else:
                self._log("  [4/4] No LLM available — skipping custom parser step")

        # ── Assemble result ──────────────────────────────────────────
        discovery = self._build_discovery(
            path, probe, schema, hints, cs,
            custom_parser_path, converted_csv_path
        )
        self._log(f"✅ Done. Format={discovery.confirmed_format}  "
                  f"Usable={discovery.is_usable()}")
        return discovery

    # ---------------------------------------------------------------- #
    # LLM custom parser                                                 #
    # ---------------------------------------------------------------- #

    def _llm_custom_parser(
        self, path: str, hints: list[FormatHint], cs: ContentSample
    ) -> tuple[Optional[str], Optional[str]]:
        """
        Ask the LLM to write a custom Python parser.
        Validates it, runs it, returns (script_path, csv_output_path).
        Returns (None, None) on failure.
        """
        output_csv = os.path.join(self.work_dir, "unknown_fmt_converted.csv")

        prompt = _CUSTOM_PARSER_PROMPT.format(
            file_info=(
                f"Path: {path}\n"
                f"Size: {cs.file_size:,} bytes\n"
                f"Extension: {Path(path).suffix or '(none)'}"
            ),
            hex_dump=cs.hex_dump[:800],
            text_preview=(cs.text_head[:500] if cs.text_head else "(binary — no text preview)"),
            hints="\n".join(
                f"  [{h.format}] conf={h.confidence:.2f}  cat={h.category}"
                + (f"  notes={h.notes}" if h.notes else "")
                for h in hints[:6]
            ),
            entropy=cs.entropy,
            null_pct=cs.null_ratio,
            printable_pct=cs.printable_ratio,
        )

        max_attempts = 3
        last_error   = ""

        for attempt in range(1, max_attempts + 1):
            self._log(f"       LLM attempt {attempt}/{max_attempts}…")

            # Build message — re-inject previous error if any
            messages = [{"role": "user", "content": prompt}]
            if last_error:
                messages.append({
                    "role": "assistant",
                    "content": "# (previous attempt)"
                })
                messages.append({
                    "role": "user",
                    "content": (
                        f"That script failed with:\n{last_error}\n\n"
                        "Please fix it and return only the corrected Python code."
                    )
                })

            try:
                response = self.llm.invoke(
                    [m["content"] if isinstance(m["content"], str)
                     else m for m in messages]
                )
                code = getattr(response, "content", str(response)).strip()
                # Strip markdown fences if present
                code = _strip_fences(code)
            except Exception as e:
                self._log(f"       LLM call failed: {e}")
                return None, None

            # ── Inject path variables ────────────────────────────────
            injected = (
                f'INPUT_PATH  = {json.dumps(path)}\n'
                f'OUTPUT_PATH = {json.dumps(output_csv)}\n\n'
                + code
            )

            # ── Syntax check ─────────────────────────────────────────
            try:
                import ast
                ast.parse(injected)
            except SyntaxError as e:
                last_error = f"SyntaxError: {e}"
                self._log(f"       Syntax error: {e}")
                continue

            # ── Save and execute ──────────────────────────────────────
            script_path = os.path.join(
                self.work_dir, f"custom_parser_attempt_{attempt}.py"
            )
            with open(script_path, "w") as f:
                f.write(injected)

            try:
                proc = subprocess.run(
                    [sys.executable, script_path],
                    capture_output=True, text=True, timeout=60,
                )
                if proc.returncode == 0 and os.path.isfile(output_csv):
                    return script_path, output_csv
                last_error = (proc.stderr or proc.stdout)[:400]
                self._log(f"       Script failed: {last_error[:120]}")
            except subprocess.TimeoutExpired:
                last_error = "Script timed out after 60s"
                self._log(f"       {last_error}")

        return None, None

    # ---------------------------------------------------------------- #
    # Build discovery object                                            #
    # ---------------------------------------------------------------- #

    def _build_discovery(
        self,
        path: str,
        probe: ProbeResult,
        schema: Optional[SchemaReport],
        hints: list[FormatHint],
        cs: ContentSample,
        custom_parser_path: Optional[str],
        converted_csv_path: Optional[str],
    ) -> FormatDiscovery:

        routing: dict = {}
        targets: list[str] = []
        warnings: list[str] = list(probe.parse_warnings)

        if schema:
            routing = schema.routing_hints
            targets = schema.target_candidates

        discovery = FormatDiscovery(
            original_path=path,
            confirmed_format=probe.format,
            category=probe.category,
            parser_used=probe.parser_used,
            schema=schema,
            custom_parser_path=custom_parser_path,
            converted_csv_path=converted_csv_path,
            routing_hints=routing,
            target_candidates=targets,
            confidence=probe.confidence,
            warnings=warnings,
        )

        # ── Summary text ─────────────────────────────────────────────
        lines = [
            "=" * 60,
            "🔍 UNKNOWN FORMAT AGENT — DISCOVERY REPORT",
            "=" * 60,
            f"File        : {os.path.basename(path)}",
            f"Format      : {probe.format}  (confidence {probe.confidence:.0%})",
            f"Category    : {probe.category}",
            f"Parser      : {probe.parser_used}",
        ]

        if hints:
            top = [(h.format, round(h.confidence, 2)) for h in hints[:4]]
            lines.append(f"Sniff hints : {top}")

        if cs.structure_notes:
            lines.append(f"Content     : {' | '.join(cs.structure_notes[:3])}")

        if custom_parser_path:
            lines.append(f"Custom parser: {custom_parser_path}")
        if converted_csv_path:
            lines.append(f"Converted CSV: {converted_csv_path}")

        if schema and schema.summary_text:
            lines.append("")
            lines.append(schema.summary_text)
        elif probe.raw_schema:
            lines.append(f"\nSchema:\n{probe.raw_schema}")

        if warnings:
            lines.append(f"\nWarnings: {warnings}")

        if routing:
            lines.append(f"\nRouting hints: {routing}")
        if targets:
            lines.append(f"Target candidates: {targets}")

        lines.append("=" * 60)
        discovery.summary_text = "\n".join(lines)
        return discovery

    # ---------------------------------------------------------------- #
    # Helpers                                                           #
    # ---------------------------------------------------------------- #

    def _log(self, msg: str):
        if self.verbose:
            print(f"[UnknownFormatAgent] {msg}")


def _strip_fences(code: str) -> str:
    """Remove ```python ... ``` or ``` ... ``` wrappers from LLM output."""
    code = code.strip()
    if code.startswith("```"):
        lines = code.splitlines()
        # Drop first line (```python or ```) and last line (```)
        if lines[-1].strip() == "```":
            lines = lines[1:-1]
        else:
            lines = lines[1:]
        code = "\n".join(lines)
    return code
